---
name: "Datarepo GitHub Actions for  umbrella helm chart release"
description: "Runs various commands via GitHub Actions."
branding:
  icon: "terminal"
  color: "purple"
inputs:
  umbrella_name:
    description: "name of the umbrella chart to be released"
    default: "datarepo"
  helm_charts:
    description: "list of helm charts you release in umbrella"
    default: "create-secret-manager-secret,gcloud-sqlproxy,datarepo-api,datarepo-ui,oidc-proxy"
runs:
  using: "docker"
  image: "./Dockerfile"
